### ISSUE TITLE
The Project.getConvention() method has been deprecated.

### ISSUE THREAD

**Issue by Goooler** [britter/maven-plugin-development#166]
```
DefaultMavenPluginDevelopmentExtension.kt:69	
  at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)	
  at de.benediktritter.maven.plugin.development.internal.DefaultMavenPluginDevelopmentExtension$pluginSourceSet$1.call(DefaultMavenPluginDevelopmentExtension.kt:69)	
  at de.benediktritter.maven.plugin.development.internal.DefaultMavenPluginDevelopmentExtension$pluginSourceSet$1.call(DefaultMavenPluginDevelopmentExtension.kt:34)	
  at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)	
  at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
```

```
MavenPluginDevelopmentPlugin.kt:154	
  at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)	
  at de.benediktritter.maven.plugin.development.MavenPluginDevelopmentPlugin$apply$1$generateTask$1$4.call(MavenPluginDevelopmentPlugin.kt:154)	
  at de.benediktritter.maven.plugin.development.MavenPluginDevelopmentPlugin$apply$1$generateTask$1$4.call(MavenPluginDevelopmentPlugin.kt:85)	
  at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)	
  at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)	
```

- Build scan: https://scans.gradle.com/s/atdqtxnmz7ce4/deprecations?expanded=WyIzIl0&expanded-stacktrace=WyI2NSIsIjYyIl0
- Version 0.4.2

**Comment by britter** [comment]
I can reproduce this in `sample/gradle-producer-build` but I'm currently unable to write a test that fails because of the deprecations.

**Comment by britter** [comment]
Tried to write a test in #200 but without success. Need to dig deeper.

**Comment by Goooler** [comment]
This is a convention invocation from older Gradle but has been polished in newer versions, check 
https://github.com/gradle/gradle/blob/1cf537a851c635c364a4214885f8b9798051175b/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ProjectExtensions.kt#L100-L112

I believe we can just replace `the` usages in #167 without any test case.
